import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import DashboardShell from "@/components/dashboard/DashboardShell";
import { getBrands, getLandingsByBrand } from "@/lib/data";
import { getSupabaseBrands } from "@/lib/supabaseBrands";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const jsonBrands = getBrands();
  const supabaseBrands = await getSupabaseBrands();
  const brands = [
    ...jsonBrands,
    ...supabaseBrands.filter(
      (supabaseBrand) =>
        !jsonBrands.some((jsonBrand) => jsonBrand.slug === supabaseBrand.slug),
    ),
  ];
  const landingSummaries = brands.flatMap((brand) =>
    getLandingsByBrand(brand.slug).map((landing) => ({
      brandSlug: brand.slug,
      landingSlug: landing.slug,
      title: landing.title,
      fullTitle: landing.fullTitle,
    })),
  );

  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body suppressHydrationWarning className="min-h-full flex flex-col">
        <DashboardShell brands={brands} landingSummaries={landingSummaries}>
          {children}
        </DashboardShell>
      </body>
    </html>
  );
}
